name: Release

on:
  push:
    branches:
      - beta
      - master

permissions: {}

jobs:
  release:
    name: Publish & Deploy
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.17

      - name: Install dependencies
        run: yarn install --frozen-lockfile --no-optional

      - name: Publish to npm
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEEK_OSS_CI_NPM_TOKEN }}
