name: Validate

on:
  - pull_request
  - push

permissions: {}

jobs:
  validate:
    name: Lint & Test
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v4
        with:
          # We're experiencing installation issues with 18.18
          node-version: 18.17

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test:ci

      - name: Lint
        run: yarn lint
